language: python
python: 3.8
cache: pip

before_install:
- pip install -r requirements/base.requirements

jobs:
  include:
  - stage: "Lint"
    script: pylint --rcfile=./app/.pylintrc ./app/

branches:
  only:
  - master
  - develop
