language: python
python: 3.8
cache: pip

before_install:
- pip install -r collector/requirements.txt

jobs:
  include:
  - stage: "Lint"
    script: pylint --rcfile=.pylintrc ./collector/app/

branches:
  only:
  - master
  - develop
